# Per a desplegar a GitHub Pages en cada push a main
name: Desplegar a GitHub Pages

on:
  push:
    branches: ["main"]

  # Permet executar manualment des de pestanya Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Permet només un desplegament actiu alhora
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurar Pages
        uses: actions/configure-pages@v4
      - name: Pujar artefacte
        uses: actions/upload-pages-artifact@v3
        with:
          # Desplegar el contingut de l'arrel del repo (que és el contingut de web/)
          path: '.'
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
